### PR TITLE
Add_E3D_Everyday_ABS to material list

### PR DESCRIPTION
**Pull request by TimVa**
**Material add:** E3D Everyday ABS
**Comment:** Initial release, use with care and communicate any improvements you may have

### CODE REVIEW

**Comment by Alex9779** [comment]
Are you sure about bride cooling at 80%?

**Comment by Alex9779** [comment]
Oh I just realised this is in my Innofil ABS too... Maybe I should think about this too...
But anyways, you printed with it, did you print bridges too?

**Comment by TimVa** [comment]
No long bridges yet.  
We should define a standard design which we can use to validate the strength, bridging.  
Can benchy be used for this?  I doubt it IMHO

**Comment by Alex9779** [comment]
Benchy has bridging, the roof when it starts... But the overall surface is small, I had cooling issues when the fan was set too high for bridges on larger bridges, though it could happen on the benchy too..
Have no experience with ABS bridges... All I printed in ABS was optimised and I think I did no cooling the whole prints...
Maybe we should reduce to 30% as a start, this won't hurt so much...

**Pull request merged**
